---

box_prometheus_exporters:
  - {
      name: apache
    }
  - {
      name: nginx
    }
  - {
      name: blackbox
    }
  - {
      name: cadvisor
    }
  - {
      name: cloudwatch
    }
  - {
      name: ecs
    }
  - {
      name: elasticsearch
    }
  - {
      name: memcached
    }
  - {
      name: mongodb
    }
  - {
      name: monit
    }
  - {
      name: mysqld
    }
  - {
    name: proxysql
    }
  - {
      name: node
    }
  - {
      name: phpfpm
    }
  - {
      name: postgres
    }
  - {
      name: redis
    }
  - {
      name: sql
    }
  - {
      name: ssl
    }
